### ISSUE TITLE
'TypeTuple' not found,

### ISSUE THREAD

**Issue by joelcnz** [buggins/dlangui-examples#2]
Just an old version of gl3n. It works with the up to date version (gl3n 1.3.1).

Joels-MacBook-Pro:helloworld joelcnz$ dub
Fetching dlangui 0.6.54 (getting selected version)...
Placing dlangui 0.6.54 to /Users/joelcnz/.dub/packages/...
Performing "debug" build using dmd for x86_64.
derelict-util 2.0.4: building configuration "library"...
derelict-ft 1.0.2: building configuration "library"...
derelict-gl3 1.0.18: building configuration "library"...
derelict-sdl2 1.9.7: building configuration "library"...
dlib 0.7.1: building configuration "library"...
../../../../../.dub/packages/dlib-0.7.1/dlib/filesystem/stdfs.d(34,8): Deprecation: module std.c.stdio is deprecated - Import core.stdc.stdio instead
dlib.container.aarray is deprecated, use dlib.container.dict instead
../../../../../.dub/packages/dlib-0.7.1/dlib/geometry/ray.d(46,5): Deprecation: constructor dlib.geometry.ray.Ray.this all parameters have default arguments, but structs cannot have default constructors.
gl3n 1.2.0: building configuration "library"...
../../../../../.dub/packages/gl3n-1.2.0/gl3n/util.d(14,12): Error: module std.typecons import 'TypeTuple' not found, did you mean template 'isTypeTuple(T...)'?
dmd failed with exit code 1.
Joels-MacBook-Pro:helloworld joelcnz$
